name: HelloWorld
on: [push]:
    pull_request:
    workflow_dispatch:



jobs:
  hello:
    name: firstjob
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "hellow world"
      - name: step2
        run: echo "this is me github acitons"
  