name: secret-demo
on: [push]
jobs:
  build:
    steps:
      - name: showing secret
        run: echo "using secret"
        env:
          TOKEN: ${{ secrets.MYSECRET_TOKEN }}
      - name: printing secret
        run: echo "${ secrets.MYSECRET_TOKEN}"
        run: echo "${{ secrets.MYSECRET_TOKEN}}"


