name: secret-demo
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: showing secret
        run: echo "using secret"
        env:
          TOKEN: ${{ secrets.MYSECRET_TOKEN }}
      - name: printing secret
        run: echo "${{ secrets.MYSECRET_TOKEN}}"


