name: conditions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: feature branch only
        if: github.ref == 'refs/heads/feature'
        run: echo "this is feature branch"

      - name: main branch only
        if: github.ref == "refs/heads/main"
        run: echo "this is main branch"
      - name: only if previous succeedd
        if: success()
        run: echo "success"

      - name: only if failed
        if: failure()
        run: echo "failed"

      - name: always
        if: always()
        run: echo "hi sameer you will be succedd"
